// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sftp$0 from "../sftp/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CancelCertOp aborts a running issue/renew/remove/install operation.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function CancelCertOp(id) {
    return $Call.ByID(415857050, id);
}

/**
 * @param {string} connectionID
 * @returns {$CancellablePromise<string>}
 */
export function ConnectSSH(connectionID) {
    return $Call.ByID(3171932001, connectionID);
}

/**
 * CreateCertTask stores a new certificate task. DNS credentials are
 * encrypted before storage.
 * @param {models$0.CertTaskForm} form
 * @returns {$CancellablePromise<models$0.CertTask>}
 */
export function CreateCertTask(form) {
    return $Call.ByID(547765062, form).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {models$0.ConnectionForm} form
 * @returns {$CancellablePromise<void>}
 */
export function CreateConnection(form) {
    return $Call.ByID(1437606669, form);
}

/**
 * @param {string} id
 * @param {string} name
 * @param {string | null} parentID
 * @param {number} sortOrder
 * @returns {$CancellablePromise<void>}
 */
export function CreateGroup(id, name, parentID, sortOrder) {
    return $Call.ByID(264129512, id, name, parentID, sortOrder);
}

/**
 * @param {string} name
 * @param {string} connectionID
 * @param {string} fwdType
 * @param {string} localHost
 * @param {number} localPort
 * @param {string} remoteHost
 * @param {number} remotePort
 * @param {boolean} autoStart
 * @returns {$CancellablePromise<models$0.PortForward>}
 */
export function CreatePortForward(name, connectionID, fwdType, localHost, localPort, remoteHost, remotePort, autoStart) {
    return $Call.ByID(171843151, name, connectionID, fwdType, localHost, localPort, remoteHost, remotePort, autoStart).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {models$0.QuickCommand} cmd
 * @returns {$CancellablePromise<void>}
 */
export function CreateQuickCommand(cmd) {
    return $Call.ByID(732401809, cmd);
}

/**
 * DeleteCertTask removes the local task only; the server keeps its acme.sh
 * config and cron renewals.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteCertTask(id) {
    return $Call.ByID(2835855333, id);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteConnection(id) {
    return $Call.ByID(1356256274, id);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteGroup(id) {
    return $Call.ByID(585039529, id);
}

/**
 * @param {string} localPath
 * @returns {$CancellablePromise<void>}
 */
export function DeleteLocalFile(localPath) {
    return $Call.ByID(2441201403, localPath);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeletePortForward(id) {
    return $Call.ByID(742144622, id);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteQuickCommand(id) {
    return $Call.ByID(1688177718, id);
}

/**
 * DeleteSSHKey removes a key file and its .pub companion from ~/.ssh.
 * If the key is in a subdirectory, the subdirectory is also removed when empty.
 * Keys still used by a connection are refused.
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function DeleteSSHKey(name) {
    return $Call.ByID(2358421539, name);
}

/**
 * DetectCertEnvironment checks acme.sh installation, cron entry and curl on
 * the target server.
 * @param {string} connectionID
 * @returns {$CancellablePromise<models$0.CertEnvironment>}
 */
export function DetectCertEnvironment(connectionID) {
    return $Call.ByID(2576399537, connectionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {string} connectionID
 * @returns {$CancellablePromise<void>}
 */
export function DisconnectSSH(connectionID) {
    return $Call.ByID(1796353151, connectionID);
}

/**
 * DisconnectSession disconnects a single terminal session. If it's the last
 * session for its connection, the full connection cleanup is also performed.
 * @param {string} sessionID
 * @param {string} connectionID
 * @returns {$CancellablePromise<void>}
 */
export function DisconnectSession(sessionID, connectionID) {
    return $Call.ByID(3227406241, sessionID, connectionID);
}

/**
 * GenerateSSHKey generates a new SSH key pair and writes it to ~/.ssh/<name>.
 * @param {string} name
 * @param {string} keyType
 * @param {number} bits
 * @param {string} comment
 * @param {string} passphrase
 * @returns {$CancellablePromise<void>}
 */
export function GenerateSSHKey(name, keyType, bits, comment, passphrase) {
    return $Call.ByID(1376428699, name, keyType, bits, comment, passphrase);
}

/**
 * GetCertServerLog tails the persistent acme.sh log on the server.
 * @param {string} connectionID
 * @returns {$CancellablePromise<string>}
 */
export function GetCertServerLog(connectionID) {
    return $Call.ByID(2547413604, connectionID);
}

/**
 * GetCertTaskCredentials decrypts and returns the stored DNS credentials for
 * the edit form's reveal button (same pattern as GetPassword).
 * @param {string} id
 * @returns {$CancellablePromise<{ [_ in string]?: string }>}
 */
export function GetCertTaskCredentials(id) {
    return $Call.ByID(3411543310, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetCertTaskLog returns the persisted log of the task's last operation so
 * the log view survives app restarts.
 * @param {string} id
 * @returns {$CancellablePromise<string>}
 */
export function GetCertTaskLog(id) {
    return $Call.ByID(2325836218, id);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetHomeDir() {
    return $Call.ByID(2930168599);
}

/**
 * GetKeyPassphrase returns the decrypted key passphrase of a connection (for the edit form's reveal).
 * @param {string} id
 * @returns {$CancellablePromise<string>}
 */
export function GetKeyPassphrase(id) {
    return $Call.ByID(1809890710, id);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<string>}
 */
export function GetPassword(id) {
    return $Call.ByID(2249946754, id);
}

/**
 * GetPrivateKey returns the decrypted private key of a connection (for the edit form's reveal).
 * @param {string} id
 * @returns {$CancellablePromise<string>}
 */
export function GetPrivateKey(id) {
    return $Call.ByID(3393968389, id);
}

/**
 * GetRemoteCertInfo returns detailed key=value info for one remote cert.
 * @param {string} connectionID
 * @param {string} domain
 * @param {boolean} ecc
 * @returns {$CancellablePromise<models$0.RemoteCertInfo | null>}
 */
export function GetRemoteCertInfo(connectionID, domain, ecc) {
    return $Call.ByID(211274131, connectionID, domain, ecc).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetSSHConfigHostDetail returns full details for a single Host entry from ~/.ssh/config, including private key content.
 * @param {string} pattern
 * @returns {$CancellablePromise<$models.SSHConfigHostDetail | null>}
 */
export function GetSSHConfigHostDetail(pattern) {
    return $Call.ByID(4214989274, pattern).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * GetSSHConfigImportCandidates parses ~/.ssh/config and returns Host blocks as importable connection candidates.
 * @returns {$CancellablePromise<$models.SSHConfigImportCandidate[]>}
 */
export function GetSSHConfigImportCandidates() {
    return $Call.ByID(3643830274).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * GetSSHKeyUsage returns names of connections currently using the given key.
 * The frontend calls this before deletion to show an i18n'd "in use" message.
 * @param {string} name
 * @returns {$CancellablePromise<string[]>}
 */
export function GetSSHKeyUsage(name) {
    return $Call.ByID(1439721781, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * ImportSSHConfigHosts imports selected Host entries from ~/.ssh/config as vShell connections.
 * @param {string[]} patterns
 * @returns {$CancellablePromise<void>}
 */
export function ImportSSHConfigHosts(patterns) {
    return $Call.ByID(4221413695, patterns);
}

/**
 * @returns {$CancellablePromise<models$0.PortForward[]>}
 */
export function ListAllPortForwards() {
    return $Call.ByID(4070239221).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * ListCertTasks returns all local certificate tasks with connection info.
 * @returns {$CancellablePromise<models$0.CertTask[]>}
 */
export function ListCertTasks() {
    return $Call.ByID(3300107467).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * @returns {$CancellablePromise<models$0.Connection[]>}
 */
export function ListConnections() {
    return $Call.ByID(2436681430).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * ListDNSProviders returns the DNS provider registry for dynamic form
 * rendering.
 * @returns {$CancellablePromise<models$0.DNSProvider[]>}
 */
export function ListDNSProviders() {
    return $Call.ByID(724386694).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType16($result);
    }));
}

/**
 * @returns {$CancellablePromise<models$0.Group[]>}
 */
export function ListGroups() {
    return $Call.ByID(494692261).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType18($result);
    }));
}

/**
 * @param {string} dirPath
 * @returns {$CancellablePromise<$models.LocalFileInfo[]>}
 */
export function ListLocalDir(dirPath) {
    return $Call.ByID(1378612327, dirPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType20($result);
    }));
}

/**
 * @param {string} connectionID
 * @returns {$CancellablePromise<models$0.PortForward[]>}
 */
export function ListPortForwards(connectionID) {
    return $Call.ByID(3400329328, connectionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * @param {string | null} connectionID
 * @returns {$CancellablePromise<models$0.QuickCommand[]>}
 */
export function ListQuickCommands(connectionID) {
    return $Call.ByID(3567644202, connectionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType22($result);
    }));
}

/**
 * ListRemoteCerts lists the certs managed by acme.sh on the server,
 * enriched with renewal dates.
 * @param {string} connectionID
 * @returns {$CancellablePromise<models$0.RemoteCert[]>}
 */
export function ListRemoteCerts(connectionID) {
    return $Call.ByID(1241534342, connectionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType24($result);
    }));
}

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function ListRunningPortForwards() {
    return $Call.ByID(3835552541).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * ListSSHKeys scans ~/.ssh and its subdirectories for private key files and returns their metadata.
 * @returns {$CancellablePromise<$models.SSHKeyInfo[]>}
 */
export function ListSSHKeys() {
    return $Call.ByID(3301404409).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType26($result);
    }));
}

/**
 * MoveConnection updates just the group_id of a connection (for drag-and-drop reordering).
 * @param {string} connectionID
 * @param {string | null} groupID
 * @returns {$CancellablePromise<void>}
 */
export function MoveConnection(connectionID, groupID) {
    return $Call.ByID(2001249400, connectionID, groupID);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function OpenInFileManager(path) {
    return $Call.ByID(1212571871, path);
}

/**
 * @param {string} localPath
 * @returns {$CancellablePromise<string>}
 */
export function ReadLocalFileContent(localPath) {
    return $Call.ByID(183856699, localPath);
}

/**
 * ReadSSHConfig parses ~/.ssh/config and returns structured entries.
 * @returns {$CancellablePromise<$models.SSHConfigEntry[]>}
 */
export function ReadSSHConfig() {
    return $Call.ByID(3639124279).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType28($result);
    }));
}

/**
 * ReadSSHConfigRaw returns the raw content of ~/.ssh/config.
 * @returns {$CancellablePromise<string>}
 */
export function ReadSSHConfigRaw() {
    return $Call.ByID(1473160119);
}

/**
 * ReadSSHKeyContent returns the public key or private key content.
 * kind = "pub" returns the .pub file, kind = "private" returns the private key.
 * @param {string} name
 * @param {string} kind
 * @returns {$CancellablePromise<string>}
 */
export function ReadSSHKeyContent(name, kind) {
    return $Call.ByID(1669966985, name, kind);
}

/**
 * RenameSSHKey renames a key file and its .pub companion in ~/.ssh.
 * @param {string} oldName
 * @param {string} newName
 * @returns {$CancellablePromise<void>}
 */
export function RenameSSHKey(oldName, newName) {
    return $Call.ByID(867475454, oldName, newName);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function SFTPCancelTransfers() {
    return $Call.ByID(2767088298);
}

/**
 * @param {string} connectionID
 * @param {string} remotePath
 * @returns {$CancellablePromise<void>}
 */
export function SFTPDelete(connectionID, remotePath) {
    return $Call.ByID(1494492831, connectionID, remotePath);
}

/**
 * @param {string} connectionID
 * @param {string} remotePath
 * @param {string} localPath
 * @returns {$CancellablePromise<void>}
 */
export function SFTPDownload(connectionID, remotePath, localPath) {
    return $Call.ByID(3634276412, connectionID, remotePath, localPath);
}

/**
 * @param {string} connectionID
 * @param {string} path
 * @returns {$CancellablePromise<sftp$0.FileInfo[]>}
 */
export function SFTPReadDir(connectionID, path) {
    return $Call.ByID(3242100799, connectionID, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType30($result);
    }));
}

/**
 * @param {string} connectionID
 * @param {string} remotePath
 * @returns {$CancellablePromise<string>}
 */
export function SFTPReadFileContent(connectionID, remotePath) {
    return $Call.ByID(2657354111, connectionID, remotePath);
}

/**
 * @param {string} connectionID
 * @param {string} localPath
 * @param {string} remotePath
 * @returns {$CancellablePromise<void>}
 */
export function SFTPUpload(connectionID, localPath, remotePath) {
    return $Call.ByID(1896528085, connectionID, localPath, remotePath);
}

/**
 * @param {string} connectionID
 * @param {string} remotePath
 * @param {string} content
 * @returns {$CancellablePromise<void>}
 */
export function SFTPWriteFileContent(connectionID, remotePath, content) {
    return $Call.ByID(952444442, connectionID, remotePath, content);
}

/**
 * SaveSSHKey writes a private key (and optional .pub) to ~/.ssh/<name>.
 * @param {string} name
 * @param {string} privateKey
 * @param {string} publicKey
 * @returns {$CancellablePromise<void>}
 */
export function SaveSSHKey(name, privateKey, publicKey) {
    return $Call.ByID(3774081477, name, privateKey, publicKey);
}

/**
 * SetApp sets the Wails application reference. Called after application creation.
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function SetApp(app) {
    return $Call.ByID(4209028258, app);
}

/**
 * StartAcmeShInstall installs acme.sh on the server; progress arrives via
 * cert:log / cert:stage / cert:op-done events.
 * @param {string} connectionID
 * @param {string} email
 * @returns {$CancellablePromise<string>}
 */
export function StartAcmeShInstall(connectionID, email) {
    return $Call.ByID(3628445521, connectionID, email);
}

/**
 * StartCertIssue runs the full issuance flow for a stored task. email is
 * only used when acme.sh has to be installed first.
 * @param {string} taskID
 * @param {string} email
 * @returns {$CancellablePromise<string>}
 */
export function StartCertIssue(taskID, email) {
    return $Call.ByID(3847721356, taskID, email);
}

/**
 * StartCertRemove removes the cert from acme.sh on the server and,
 * optionally, deletes the local task as well.
 * @param {string} taskID
 * @param {boolean} deleteTask
 * @returns {$CancellablePromise<string>}
 */
export function StartCertRemove(taskID, deleteTask) {
    return $Call.ByID(1688282169, taskID, deleteTask);
}

/**
 * StartCertRenew forces an immediate renewal of a stored task.
 * @param {string} taskID
 * @returns {$CancellablePromise<string>}
 */
export function StartCertRenew(taskID) {
    return $Call.ByID(404074634, taskID);
}

/**
 * @param {string} connectionID
 * @returns {$CancellablePromise<void>}
 */
export function StartMonitor(connectionID) {
    return $Call.ByID(2280921331, connectionID);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function StartPortForward(id) {
    return $Call.ByID(2842386481, id);
}

/**
 * @param {string} connectionID
 * @returns {$CancellablePromise<void>}
 */
export function StopMonitor(connectionID) {
    return $Call.ByID(1136101429, connectionID);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function StopPortForward(id) {
    return $Call.ByID(3174015391, id);
}

/**
 * UpdateCertTask updates an existing task. Empty DNS credentials keep the
 * stored ones (same convention as connection secrets).
 * @param {models$0.CertTaskForm} form
 * @returns {$CancellablePromise<models$0.CertTask>}
 */
export function UpdateCertTask(form) {
    return $Call.ByID(2065196927, form).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {models$0.ConnectionForm} form
 * @returns {$CancellablePromise<void>}
 */
export function UpdateConnection(form) {
    return $Call.ByID(3356068760, form);
}

/**
 * @param {string} id
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function UpdateGroup(id, name) {
    return $Call.ByID(905940643, id, name);
}

/**
 * @param {string} id
 * @param {string} name
 * @param {string} connectionID
 * @param {string} fwdType
 * @param {string} localHost
 * @param {number} localPort
 * @param {string} remoteHost
 * @param {number} remotePort
 * @param {boolean} autoStart
 * @returns {$CancellablePromise<void>}
 */
export function UpdatePortForward(id, name, connectionID, fwdType, localHost, localPort, remoteHost, remotePort, autoStart) {
    return $Call.ByID(1560667840, id, name, connectionID, fwdType, localHost, localPort, remoteHost, remotePort, autoStart);
}

/**
 * @param {string} localPath
 * @param {string} content
 * @returns {$CancellablePromise<void>}
 */
export function WriteLocalFileContent(localPath, content) {
    return $Call.ByID(3166138842, localPath, content);
}

/**
 * WriteSSHConfig serializes entries back to ~/.ssh/config.
 * @param {$models.SSHConfigEntry[]} entries
 * @returns {$CancellablePromise<void>}
 */
export function WriteSSHConfig(entries) {
    return $Call.ByID(1250750292, entries);
}

/**
 * WriteSSHConfigRaw writes raw content to ~/.ssh/config.
 * @param {string} content
 * @returns {$CancellablePromise<void>}
 */
export function WriteSSHConfigRaw(content) {
    return $Call.ByID(803427770, content);
}

// Private type creation functions
const $$createType0 = models$0.CertTask.createFrom;
const $$createType1 = models$0.PortForward.createFrom;
const $$createType2 = models$0.CertEnvironment.createFrom;
const $$createType3 = $Create.Map($Create.Any, $Create.Any);
const $$createType4 = models$0.RemoteCertInfo.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $models.SSHConfigHostDetail.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $models.SSHConfigImportCandidate.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = $Create.Array($Create.Any);
const $$createType11 = $Create.Array($$createType1);
const $$createType12 = $Create.Array($$createType0);
const $$createType13 = models$0.Connection.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = models$0.DNSProvider.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = models$0.Group.createFrom;
const $$createType18 = $Create.Array($$createType17);
const $$createType19 = $models.LocalFileInfo.createFrom;
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = models$0.QuickCommand.createFrom;
const $$createType22 = $Create.Array($$createType21);
const $$createType23 = models$0.RemoteCert.createFrom;
const $$createType24 = $Create.Array($$createType23);
const $$createType25 = $models.SSHKeyInfo.createFrom;
const $$createType26 = $Create.Array($$createType25);
const $$createType27 = $models.SSHConfigEntry.createFrom;
const $$createType28 = $Create.Array($$createType27);
const $$createType29 = sftp$0.FileInfo.createFrom;
const $$createType30 = $Create.Array($$createType29);
