// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sftp$0 from "../sftp/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ConnectSSH(connectionID: string): $CancellablePromise<string> {
    return $Call.ByID(3171932001, connectionID);
}

export function CreateConnection(form: models$0.ConnectionForm): $CancellablePromise<void> {
    return $Call.ByID(1437606669, form);
}

export function CreateGroup(id: string, name: string, parentID: string | null, sortOrder: number): $CancellablePromise<void> {
    return $Call.ByID(264129512, id, name, parentID, sortOrder);
}

export function CreatePortForward(name: string, connectionID: string, fwdType: string, localHost: string, localPort: number, remoteHost: string, remotePort: number, autoStart: boolean): $CancellablePromise<models$0.PortForward> {
    return $Call.ByID(171843151, name, connectionID, fwdType, localHost, localPort, remoteHost, remotePort, autoStart).then(($result: any) => {
        return $$createType0($result);
    });
}

export function CreateQuickCommand(cmd: models$0.QuickCommand): $CancellablePromise<void> {
    return $Call.ByID(732401809, cmd);
}

export function DeleteConnection(id: string): $CancellablePromise<void> {
    return $Call.ByID(1356256274, id);
}

export function DeleteGroup(id: string): $CancellablePromise<void> {
    return $Call.ByID(585039529, id);
}

export function DeleteLocalFile(localPath: string): $CancellablePromise<void> {
    return $Call.ByID(2441201403, localPath);
}

export function DeletePortForward(id: string): $CancellablePromise<void> {
    return $Call.ByID(742144622, id);
}

export function DeleteQuickCommand(id: string): $CancellablePromise<void> {
    return $Call.ByID(1688177718, id);
}

/**
 * DeleteSSHKey removes a key file and its .pub companion from ~/.ssh.
 */
export function DeleteSSHKey(name: string): $CancellablePromise<void> {
    return $Call.ByID(2358421539, name);
}

export function DisconnectSSH(connectionID: string): $CancellablePromise<void> {
    return $Call.ByID(1796353151, connectionID);
}

/**
 * DisconnectSession disconnects a single terminal session. If it's the last
 * session for its connection, the full connection cleanup is also performed.
 */
export function DisconnectSession(sessionID: string, connectionID: string): $CancellablePromise<void> {
    return $Call.ByID(3227406241, sessionID, connectionID);
}

/**
 * GenerateSSHKey generates a new SSH key pair and writes it to ~/.ssh/<name>.
 */
export function GenerateSSHKey(name: string, keyType: string, bits: number, comment: string, passphrase: string): $CancellablePromise<void> {
    return $Call.ByID(1376428699, name, keyType, bits, comment, passphrase);
}

export function GetHomeDir(): $CancellablePromise<string> {
    return $Call.ByID(2930168599);
}

export function GetPassword(id: string): $CancellablePromise<string> {
    return $Call.ByID(2249946754, id);
}

/**
 * GetSSHConfigImportCandidates parses ~/.ssh/config and returns Host blocks as importable connection candidates.
 */
export function GetSSHConfigImportCandidates(): $CancellablePromise<$models.SSHConfigImportCandidate[]> {
    return $Call.ByID(3643830274).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * ImportSSHConfigHosts imports selected Host entries from ~/.ssh/config as vShell connections.
 */
export function ImportSSHConfigHosts(patterns: string[]): $CancellablePromise<void> {
    return $Call.ByID(4221413695, patterns);
}

export function ListAllPortForwards(): $CancellablePromise<models$0.PortForward[]> {
    return $Call.ByID(4070239221).then(($result: any) => {
        return $$createType3($result);
    });
}

export function ListConnections(): $CancellablePromise<models$0.Connection[]> {
    return $Call.ByID(2436681430).then(($result: any) => {
        return $$createType5($result);
    });
}

export function ListGroups(): $CancellablePromise<models$0.Group[]> {
    return $Call.ByID(494692261).then(($result: any) => {
        return $$createType7($result);
    });
}

export function ListLocalDir(dirPath: string): $CancellablePromise<$models.LocalFileInfo[]> {
    return $Call.ByID(1378612327, dirPath).then(($result: any) => {
        return $$createType9($result);
    });
}

export function ListPortForwards(connectionID: string): $CancellablePromise<models$0.PortForward[]> {
    return $Call.ByID(3400329328, connectionID).then(($result: any) => {
        return $$createType3($result);
    });
}

export function ListQuickCommands(connectionID: string | null): $CancellablePromise<models$0.QuickCommand[]> {
    return $Call.ByID(3567644202, connectionID).then(($result: any) => {
        return $$createType11($result);
    });
}

export function ListRunningPortForwards(): $CancellablePromise<string[]> {
    return $Call.ByID(3835552541).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * ListSSHKeys scans ~/.ssh for private key files and returns their metadata.
 */
export function ListSSHKeys(): $CancellablePromise<$models.SSHKeyInfo[]> {
    return $Call.ByID(3301404409).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * MoveConnection updates just the group_id of a connection (for drag-and-drop reordering).
 */
export function MoveConnection(connectionID: string, groupID: string | null): $CancellablePromise<void> {
    return $Call.ByID(2001249400, connectionID, groupID);
}

export function ReadLocalFileContent(localPath: string): $CancellablePromise<string> {
    return $Call.ByID(183856699, localPath);
}

/**
 * ReadSSHConfig parses ~/.ssh/config and returns structured entries.
 */
export function ReadSSHConfig(): $CancellablePromise<$models.SSHConfigEntry[]> {
    return $Call.ByID(3639124279).then(($result: any) => {
        return $$createType16($result);
    });
}

/**
 * ReadSSHConfigRaw returns the raw content of ~/.ssh/config.
 */
export function ReadSSHConfigRaw(): $CancellablePromise<string> {
    return $Call.ByID(1473160119);
}

/**
 * ReadSSHKeyContent returns the public key or private key content.
 * kind = "pub" returns the .pub file, kind = "private" returns the private key.
 */
export function ReadSSHKeyContent(name: string, kind: string): $CancellablePromise<string> {
    return $Call.ByID(1669966985, name, kind);
}

/**
 * RenameSSHKey renames a key file and its .pub companion in ~/.ssh.
 */
export function RenameSSHKey(oldName: string, newName: string): $CancellablePromise<void> {
    return $Call.ByID(867475454, oldName, newName);
}

export function SFTPDelete(connectionID: string, remotePath: string): $CancellablePromise<void> {
    return $Call.ByID(1494492831, connectionID, remotePath);
}

export function SFTPDownload(connectionID: string, remotePath: string, localPath: string): $CancellablePromise<void> {
    return $Call.ByID(3634276412, connectionID, remotePath, localPath);
}

export function SFTPReadDir(connectionID: string, path: string): $CancellablePromise<sftp$0.FileInfo[]> {
    return $Call.ByID(3242100799, connectionID, path).then(($result: any) => {
        return $$createType18($result);
    });
}

export function SFTPReadFileContent(connectionID: string, remotePath: string): $CancellablePromise<string> {
    return $Call.ByID(2657354111, connectionID, remotePath);
}

export function SFTPUpload(connectionID: string, localPath: string, remotePath: string): $CancellablePromise<void> {
    return $Call.ByID(1896528085, connectionID, localPath, remotePath);
}

export function SFTPWriteFileContent(connectionID: string, remotePath: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(952444442, connectionID, remotePath, content);
}

/**
 * SaveSSHKey writes a private key (and optional .pub) to ~/.ssh/<name>.
 */
export function SaveSSHKey(name: string, privateKey: string, publicKey: string): $CancellablePromise<void> {
    return $Call.ByID(3774081477, name, privateKey, publicKey);
}

/**
 * SetApp sets the Wails application reference. Called after application creation.
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(4209028258, app);
}

export function StartMonitor(connectionID: string): $CancellablePromise<void> {
    return $Call.ByID(2280921331, connectionID);
}

export function StartPortForward(id: string): $CancellablePromise<void> {
    return $Call.ByID(2842386481, id);
}

export function StopMonitor(connectionID: string): $CancellablePromise<void> {
    return $Call.ByID(1136101429, connectionID);
}

export function StopPortForward(id: string): $CancellablePromise<void> {
    return $Call.ByID(3174015391, id);
}

export function UpdateConnection(form: models$0.ConnectionForm): $CancellablePromise<void> {
    return $Call.ByID(3356068760, form);
}

export function UpdateGroup(id: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(905940643, id, name);
}

export function UpdatePortForward(id: string, name: string, connectionID: string, fwdType: string, localHost: string, localPort: number, remoteHost: string, remotePort: number, autoStart: boolean): $CancellablePromise<void> {
    return $Call.ByID(1560667840, id, name, connectionID, fwdType, localHost, localPort, remoteHost, remotePort, autoStart);
}

export function WriteLocalFileContent(localPath: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(3166138842, localPath, content);
}

/**
 * WriteSSHConfig serializes entries back to ~/.ssh/config.
 */
export function WriteSSHConfig(entries: $models.SSHConfigEntry[]): $CancellablePromise<void> {
    return $Call.ByID(1250750292, entries);
}

/**
 * WriteSSHConfigRaw writes raw content to ~/.ssh/config.
 */
export function WriteSSHConfigRaw(content: string): $CancellablePromise<void> {
    return $Call.ByID(803427770, content);
}

// Private type creation functions
const $$createType0 = models$0.PortForward.createFrom;
const $$createType1 = $models.SSHConfigImportCandidate.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($$createType0);
const $$createType4 = models$0.Connection.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = models$0.Group.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $models.LocalFileInfo.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = models$0.QuickCommand.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = $Create.Array($Create.Any);
const $$createType13 = $models.SSHKeyInfo.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = $models.SSHConfigEntry.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = sftp$0.FileInfo.createFrom;
const $$createType18 = $Create.Array($$createType17);
