// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sftp$0 from "../sftp/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ConnectSSH(connectionID: string): $CancellablePromise<void> {
    return $Call.ByID(3171932001, connectionID);
}

export function CreateConnection(form: models$0.ConnectionForm): $CancellablePromise<void> {
    return $Call.ByID(1437606669, form);
}

export function CreateGroup(id: string, name: string, parentID: string | null, sortOrder: number): $CancellablePromise<void> {
    return $Call.ByID(264129512, id, name, parentID, sortOrder);
}

export function CreateQuickCommand(cmd: models$0.QuickCommand): $CancellablePromise<void> {
    return $Call.ByID(732401809, cmd);
}

export function DeleteConnection(id: string): $CancellablePromise<void> {
    return $Call.ByID(1356256274, id);
}

export function DeleteGroup(id: string): $CancellablePromise<void> {
    return $Call.ByID(585039529, id);
}

export function DeleteLocalFile(localPath: string): $CancellablePromise<void> {
    return $Call.ByID(2441201403, localPath);
}

export function DeleteQuickCommand(id: string): $CancellablePromise<void> {
    return $Call.ByID(1688177718, id);
}

export function DisconnectSSH(connectionID: string): $CancellablePromise<void> {
    return $Call.ByID(1796353151, connectionID);
}

export function GetHomeDir(): $CancellablePromise<string> {
    return $Call.ByID(2930168599);
}

export function ListConnections(): $CancellablePromise<models$0.Connection[]> {
    return $Call.ByID(2436681430).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ListGroups(): $CancellablePromise<models$0.Group[]> {
    return $Call.ByID(494692261).then(($result: any) => {
        return $$createType3($result);
    });
}

export function ListLocalDir(dirPath: string): $CancellablePromise<$models.LocalFileInfo[]> {
    return $Call.ByID(1378612327, dirPath).then(($result: any) => {
        return $$createType5($result);
    });
}

export function ListPortForwards(connectionID: string): $CancellablePromise<models$0.PortForward[]> {
    return $Call.ByID(3400329328, connectionID).then(($result: any) => {
        return $$createType7($result);
    });
}

export function ListQuickCommands(connectionID: string | null): $CancellablePromise<models$0.QuickCommand[]> {
    return $Call.ByID(3567644202, connectionID).then(($result: any) => {
        return $$createType9($result);
    });
}

export function SFTPDelete(connectionID: string, remotePath: string): $CancellablePromise<void> {
    return $Call.ByID(1494492831, connectionID, remotePath);
}

export function SFTPDownload(connectionID: string, remotePath: string, localPath: string): $CancellablePromise<void> {
    return $Call.ByID(3634276412, connectionID, remotePath, localPath);
}

export function SFTPReadDir(connectionID: string, path: string): $CancellablePromise<sftp$0.FileInfo[]> {
    return $Call.ByID(3242100799, connectionID, path).then(($result: any) => {
        return $$createType11($result);
    });
}

export function SFTPUpload(connectionID: string, localPath: string, remotePath: string): $CancellablePromise<void> {
    return $Call.ByID(1896528085, connectionID, localPath, remotePath);
}

/**
 * SetApp sets the Wails application reference. Called after application creation.
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(4209028258, app);
}

export function StartMonitor(connectionID: string): $CancellablePromise<void> {
    return $Call.ByID(2280921331, connectionID);
}

export function StopMonitor(connectionID: string): $CancellablePromise<void> {
    return $Call.ByID(1136101429, connectionID);
}

export function UpdateConnection(form: models$0.ConnectionForm): $CancellablePromise<void> {
    return $Call.ByID(3356068760, form);
}

// Private type creation functions
const $$createType0 = models$0.Connection.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = models$0.Group.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.LocalFileInfo.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = models$0.PortForward.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = models$0.QuickCommand.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = sftp$0.FileInfo.createFrom;
const $$createType11 = $Create.Array($$createType10);
