// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class LocalFileInfo {
    /**
     * Creates a new LocalFileInfo instance.
     * @param {Partial<LocalFileInfo>} [$$source = {}] - The source object to create the LocalFileInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("mode" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["mode"] = 0;
        }
        if (!("mod_time" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["mod_time"] = 0;
        }
        if (!("is_dir" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_dir"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LocalFileInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LocalFileInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LocalFileInfo(/** @type {Partial<LocalFileInfo>} */($$parsedSource));
    }
}

/**
 * SSHConfigDirective represents a single key-value directive within an SSH config block.
 */
export class SSHConfigDirective {
    /**
     * Creates a new SSHConfigDirective instance.
     * @param {Partial<SSHConfigDirective>} [$$source = {}] - The source object to create the SSHConfigDirective.
     */
    constructor($$source = {}) {
        if (!("key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["key"] = "";
        }
        if (!("value" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["value"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SSHConfigDirective instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SSHConfigDirective}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SSHConfigDirective(/** @type {Partial<SSHConfigDirective>} */($$parsedSource));
    }
}

/**
 * SSHConfigEntry represents a single Host or Match block from ~/.ssh/config.
 */
export class SSHConfigEntry {
    /**
     * Creates a new SSHConfigEntry instance.
     * @param {Partial<SSHConfigEntry>} [$$source = {}] - The source object to create the SSHConfigEntry.
     */
    constructor($$source = {}) {
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("pattern" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["pattern"] = "";
        }
        if (!("directives" in $$source)) {
            /**
             * @member
             * @type {SSHConfigDirective[]}
             */
            this["directives"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SSHConfigEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SSHConfigEntry}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("directives" in $$parsedSource) {
            $$parsedSource["directives"] = $$createField2_0($$parsedSource["directives"]);
        }
        return new SSHConfigEntry(/** @type {Partial<SSHConfigEntry>} */($$parsedSource));
    }
}

/**
 * SSHConfigHostDetail contains full info for a single SSH config Host entry, including private key content.
 */
export class SSHConfigHostDetail {
    /**
     * Creates a new SSHConfigHostDetail instance.
     * @param {Partial<SSHConfigHostDetail>} [$$source = {}] - The source object to create the SSHConfigHostDetail.
     */
    constructor($$source = {}) {
        if (!("pattern" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["pattern"] = "";
        }
        if (!("hostname" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hostname"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("user" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["user"] = "";
        }
        if (!("private_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["private_key"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SSHConfigHostDetail instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SSHConfigHostDetail}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SSHConfigHostDetail(/** @type {Partial<SSHConfigHostDetail>} */($$parsedSource));
    }
}

/**
 * SSHConfigImportCandidate represents a Host entry from ~/.ssh/config that can be imported as a vShell connection.
 */
export class SSHConfigImportCandidate {
    /**
     * Creates a new SSHConfigImportCandidate instance.
     * @param {Partial<SSHConfigImportCandidate>} [$$source = {}] - The source object to create the SSHConfigImportCandidate.
     */
    constructor($$source = {}) {
        if (!("pattern" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["pattern"] = "";
        }
        if (!("hostname" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hostname"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("user" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["user"] = "";
        }
        if (!("identity_file" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["identity_file"] = "";
        }
        if (!("has_key" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["has_key"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SSHConfigImportCandidate instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SSHConfigImportCandidate}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SSHConfigImportCandidate(/** @type {Partial<SSHConfigImportCandidate>} */($$parsedSource));
    }
}

export class SSHKeyInfo {
    /**
     * Creates a new SSHKeyInfo instance.
     * @param {Partial<SSHKeyInfo>} [$$source = {}] - The source object to create the SSHKeyInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("fingerprint" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fingerprint"] = "";
        }
        if (!("public_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["public_key"] = "";
        }
        if (!("comment" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["comment"] = "";
        }
        if (!("has_passphrase" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["has_passphrase"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SSHKeyInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SSHKeyInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SSHKeyInfo(/** @type {Partial<SSHKeyInfo>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = SSHConfigDirective.createFrom;
const $$createType1 = $Create.Array($$createType0);
