// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class LocalFileInfo {
    "name": string;
    "path": string;
    "size": number;
    "mode": number;
    "mod_time": number;
    "is_dir": boolean;

    /** Creates a new LocalFileInfo instance. */
    constructor($$source: Partial<LocalFileInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("mode" in $$source)) {
            this["mode"] = 0;
        }
        if (!("mod_time" in $$source)) {
            this["mod_time"] = 0;
        }
        if (!("is_dir" in $$source)) {
            this["is_dir"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LocalFileInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): LocalFileInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LocalFileInfo($$parsedSource as Partial<LocalFileInfo>);
    }
}

/**
 * SSHConfigDirective represents a single key-value directive within an SSH config block.
 */
export class SSHConfigDirective {
    "key": string;
    "value": string;

    /** Creates a new SSHConfigDirective instance. */
    constructor($$source: Partial<SSHConfigDirective> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("value" in $$source)) {
            this["value"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SSHConfigDirective instance from a string or object.
     */
    static createFrom($$source: any = {}): SSHConfigDirective {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SSHConfigDirective($$parsedSource as Partial<SSHConfigDirective>);
    }
}

/**
 * SSHConfigEntry represents a single Host or Match block from ~/.ssh/config.
 */
export class SSHConfigEntry {
    "type": string;
    "pattern": string;
    "directives": SSHConfigDirective[];

    /** Creates a new SSHConfigEntry instance. */
    constructor($$source: Partial<SSHConfigEntry> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("pattern" in $$source)) {
            this["pattern"] = "";
        }
        if (!("directives" in $$source)) {
            this["directives"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SSHConfigEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): SSHConfigEntry {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("directives" in $$parsedSource) {
            $$parsedSource["directives"] = $$createField2_0($$parsedSource["directives"]);
        }
        return new SSHConfigEntry($$parsedSource as Partial<SSHConfigEntry>);
    }
}

/**
 * SSHConfigImportCandidate represents a Host entry from ~/.ssh/config that can be imported as a vShell connection.
 */
export class SSHConfigImportCandidate {
    "pattern": string;
    "hostname": string;
    "port": number;
    "user": string;
    "identity_file": string;
    "has_key": boolean;

    /** Creates a new SSHConfigImportCandidate instance. */
    constructor($$source: Partial<SSHConfigImportCandidate> = {}) {
        if (!("pattern" in $$source)) {
            this["pattern"] = "";
        }
        if (!("hostname" in $$source)) {
            this["hostname"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("user" in $$source)) {
            this["user"] = "";
        }
        if (!("identity_file" in $$source)) {
            this["identity_file"] = "";
        }
        if (!("has_key" in $$source)) {
            this["has_key"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SSHConfigImportCandidate instance from a string or object.
     */
    static createFrom($$source: any = {}): SSHConfigImportCandidate {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SSHConfigImportCandidate($$parsedSource as Partial<SSHConfigImportCandidate>);
    }
}

export class SSHKeyInfo {
    "name": string;
    "type": string;
    "fingerprint": string;
    "public_key": string;
    "comment": string;
    "has_passphrase": boolean;

    /** Creates a new SSHKeyInfo instance. */
    constructor($$source: Partial<SSHKeyInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("fingerprint" in $$source)) {
            this["fingerprint"] = "";
        }
        if (!("public_key" in $$source)) {
            this["public_key"] = "";
        }
        if (!("comment" in $$source)) {
            this["comment"] = "";
        }
        if (!("has_passphrase" in $$source)) {
            this["has_passphrase"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SSHKeyInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): SSHKeyInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SSHKeyInfo($$parsedSource as Partial<SSHKeyInfo>);
    }
}

// Private type creation functions
const $$createType0 = SSHConfigDirective.createFrom;
const $$createType1 = $Create.Array($$createType0);
