// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class LocalFileInfo {
    "name": string;
    "path": string;
    "size": number;
    "mode": number;
    "mod_time": number;
    "is_dir": boolean;

    /** Creates a new LocalFileInfo instance. */
    constructor($$source: Partial<LocalFileInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("mode" in $$source)) {
            this["mode"] = 0;
        }
        if (!("mod_time" in $$source)) {
            this["mod_time"] = 0;
        }
        if (!("is_dir" in $$source)) {
            this["is_dir"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LocalFileInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): LocalFileInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LocalFileInfo($$parsedSource as Partial<LocalFileInfo>);
    }
}
