// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

export enum AuthType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AuthPassword = "password",
    AuthPrivateKey = "private_key",
    AuthAgent = "agent",
    AuthInteractive = "interactive",
};

export class Connection {
    "id": string;
    "group_id": string | null;
    "name": string;
    "host": string;
    "port": number;
    "username": string;
    "auth_type": AuthType;
    "proxy_type": string | null;
    "proxy_addr": string | null;
    "jump_host_id": string | null;
    "upload_path": string;
    "default_cmd": string | null;
    "sort_order": number;
    "color": string | null;
    "last_used_at": time$0.Time | null;
    "created_at": time$0.Time;
    "updated_at": time$0.Time;

    /** Creates a new Connection instance. */
    constructor($$source: Partial<Connection> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("group_id" in $$source)) {
            this["group_id"] = null;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("auth_type" in $$source)) {
            this["auth_type"] = AuthType.$zero;
        }
        if (!("proxy_type" in $$source)) {
            this["proxy_type"] = null;
        }
        if (!("proxy_addr" in $$source)) {
            this["proxy_addr"] = null;
        }
        if (!("jump_host_id" in $$source)) {
            this["jump_host_id"] = null;
        }
        if (!("upload_path" in $$source)) {
            this["upload_path"] = "";
        }
        if (!("default_cmd" in $$source)) {
            this["default_cmd"] = null;
        }
        if (!("sort_order" in $$source)) {
            this["sort_order"] = 0;
        }
        if (!("color" in $$source)) {
            this["color"] = null;
        }
        if (!("last_used_at" in $$source)) {
            this["last_used_at"] = null;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = null;
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Connection instance from a string or object.
     */
    static createFrom($$source: any = {}): Connection {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Connection($$parsedSource as Partial<Connection>);
    }
}

/**
 * ConnectionForm is used for creating/updating connections from frontend.
 */
export class ConnectionForm {
    "id": string;
    "group_id": string | null;
    "name": string;
    "host": string;
    "port": number;
    "username": string;
    "auth_type": AuthType;
    "password"?: string;
    "private_key"?: string;
    "key_passphrase"?: string;
    "proxy_type": string | null;
    "proxy_addr": string | null;
    "jump_host_id": string | null;
    "upload_path": string;
    "default_cmd": string | null;
    "sort_order": number;
    "color": string | null;

    /** Creates a new ConnectionForm instance. */
    constructor($$source: Partial<ConnectionForm> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("group_id" in $$source)) {
            this["group_id"] = null;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("auth_type" in $$source)) {
            this["auth_type"] = AuthType.$zero;
        }
        if (!("proxy_type" in $$source)) {
            this["proxy_type"] = null;
        }
        if (!("proxy_addr" in $$source)) {
            this["proxy_addr"] = null;
        }
        if (!("jump_host_id" in $$source)) {
            this["jump_host_id"] = null;
        }
        if (!("upload_path" in $$source)) {
            this["upload_path"] = "";
        }
        if (!("default_cmd" in $$source)) {
            this["default_cmd"] = null;
        }
        if (!("sort_order" in $$source)) {
            this["sort_order"] = 0;
        }
        if (!("color" in $$source)) {
            this["color"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectionForm instance from a string or object.
     */
    static createFrom($$source: any = {}): ConnectionForm {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConnectionForm($$parsedSource as Partial<ConnectionForm>);
    }
}

export enum ForwardType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ForwardLocal = "local",
    ForwardRemote = "remote",
    ForwardDynamic = "dynamic",
};

export class Group {
    "id": string;
    "name": string;
    "parent_id": string | null;
    "sort_order": number;
    "created_at": time$0.Time;
    "updated_at": time$0.Time;

    /** Creates a new Group instance. */
    constructor($$source: Partial<Group> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("parent_id" in $$source)) {
            this["parent_id"] = null;
        }
        if (!("sort_order" in $$source)) {
            this["sort_order"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = null;
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Group instance from a string or object.
     */
    static createFrom($$source: any = {}): Group {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Group($$parsedSource as Partial<Group>);
    }
}

export class PortForward {
    "id": string;
    "name": string;
    "connection_id": string;
    "connection_name": string;
    "connection_host": string;
    "type": ForwardType;
    "local_host": string;
    "local_port": number;
    "remote_host": string;
    "remote_port": number;
    "auto_start": boolean;

    /** Creates a new PortForward instance. */
    constructor($$source: Partial<PortForward> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("connection_id" in $$source)) {
            this["connection_id"] = "";
        }
        if (!("connection_name" in $$source)) {
            this["connection_name"] = "";
        }
        if (!("connection_host" in $$source)) {
            this["connection_host"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = ForwardType.$zero;
        }
        if (!("local_host" in $$source)) {
            this["local_host"] = "";
        }
        if (!("local_port" in $$source)) {
            this["local_port"] = 0;
        }
        if (!("remote_host" in $$source)) {
            this["remote_host"] = "";
        }
        if (!("remote_port" in $$source)) {
            this["remote_port"] = 0;
        }
        if (!("auto_start" in $$source)) {
            this["auto_start"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PortForward instance from a string or object.
     */
    static createFrom($$source: any = {}): PortForward {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PortForward($$parsedSource as Partial<PortForward>);
    }
}

export class QuickCommand {
    "id": string;
    "name": string;
    "command": string;
    "connection_id": string | null;
    "sort_order": number;
    "created_at": time$0.Time;
    "updated_at": time$0.Time;

    /** Creates a new QuickCommand instance. */
    constructor($$source: Partial<QuickCommand> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("command" in $$source)) {
            this["command"] = "";
        }
        if (!("connection_id" in $$source)) {
            this["connection_id"] = null;
        }
        if (!("sort_order" in $$source)) {
            this["sort_order"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = null;
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QuickCommand instance from a string or object.
     */
    static createFrom($$source: any = {}): QuickCommand {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QuickCommand($$parsedSource as Partial<QuickCommand>);
    }
}
