// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * @readonly
 * @enum {string}
 */
export const AuthType = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    AuthPassword: "password",
    AuthPrivateKey: "private_key",
    AuthAgent: "agent",
    AuthInteractive: "interactive",
};

/**
 * CertEnvironment is the result of the remote detection script.
 */
export class CertEnvironment {
    /**
     * Creates a new CertEnvironment instance.
     * @param {Partial<CertEnvironment>} [$$source = {}] - The source object to create the CertEnvironment.
     */
    constructor($$source = {}) {
        if (!("connection_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["connection_id"] = "";
        }
        if (!("home" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["home"] = "";
        }
        if (!("acme_sh_path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["acme_sh_path"] = "";
        }
        if (!("installed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["installed"] = false;
        }
        if (!("cron_present" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["cron_present"] = false;
        }
        if (!("curl_present" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["curl_present"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CertEnvironment instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CertEnvironment}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CertEnvironment(/** @type {Partial<CertEnvironment>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const CertStatus = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    CertStatusIdle: "idle",
    CertStatusRunning: "running",
    CertStatusIssued: "issued",
    CertStatusFailed: "failed",
};

/**
 * CertTask is a local record of a certificate managed by acme.sh on a remote
 * server. Credentials are stored AES-encrypted and never leave the backend.
 */
export class CertTask {
    /**
     * Creates a new CertTask instance.
     * @param {Partial<CertTask>} [$$source = {}] - The source object to create the CertTask.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("connection_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["connection_id"] = "";
        }
        if (!("connection_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["connection_name"] = "";
        }
        if (!("connection_host" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["connection_host"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("primary_domain" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["primary_domain"] = "";
        }
        if (!("san_domains" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["san_domains"] = [];
        }
        if (!("dns_provider" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dns_provider"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["dns_plugin"] = undefined;
        }
        if (!("key_length" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["key_length"] = "";
        }
        if (!("dns_sleep" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["dns_sleep"] = 0;
        }
        if (!("test_mode" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["test_mode"] = false;
        }
        if (!("auto_install" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["auto_install"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["cert_dir"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["key_file"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["fullchain_file"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["reload_cmd"] = undefined;
        }
        if (!("last_status" in $$source)) {
            /**
             * @member
             * @type {CertStatus}
             */
            this["last_status"] = CertStatus.$zero;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["last_error"] = undefined;
        }
        if (!("last_run_at" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["last_run_at"] = null;
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updated_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CertTask instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CertTask}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("san_domains" in $$parsedSource) {
            $$parsedSource["san_domains"] = $$createField6_0($$parsedSource["san_domains"]);
        }
        return new CertTask(/** @type {Partial<CertTask>} */($$parsedSource));
    }
}

/**
 * CertTaskForm is used for creating/updating cert tasks from frontend.
 * Empty DNSCredentials means "keep stored credentials" on update.
 */
export class CertTaskForm {
    /**
     * Creates a new CertTaskForm instance.
     * @param {Partial<CertTaskForm>} [$$source = {}] - The source object to create the CertTaskForm.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("connection_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["connection_id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("primary_domain" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["primary_domain"] = "";
        }
        if (!("san_domains" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["san_domains"] = [];
        }
        if (!("dns_provider" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dns_provider"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["dns_plugin"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: string } | undefined}
             */
            this["dns_credentials"] = undefined;
        }
        if (!("key_length" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["key_length"] = "";
        }
        if (!("dns_sleep" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["dns_sleep"] = 0;
        }
        if (!("test_mode" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["test_mode"] = false;
        }
        if (!("auto_install" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["auto_install"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["cert_dir"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["key_file"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["fullchain_file"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["reload_cmd"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CertTaskForm instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CertTaskForm}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType0;
        const $$createField7_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("san_domains" in $$parsedSource) {
            $$parsedSource["san_domains"] = $$createField4_0($$parsedSource["san_domains"]);
        }
        if ("dns_credentials" in $$parsedSource) {
            $$parsedSource["dns_credentials"] = $$createField7_0($$parsedSource["dns_credentials"]);
        }
        return new CertTaskForm(/** @type {Partial<CertTaskForm>} */($$parsedSource));
    }
}

export class Connection {
    /**
     * Creates a new Connection instance.
     * @param {Partial<Connection>} [$$source = {}] - The source object to create the Connection.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("group_id" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["group_id"] = null;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("host" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("username" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["username"] = "";
        }
        if (!("auth_type" in $$source)) {
            /**
             * @member
             * @type {AuthType}
             */
            this["auth_type"] = AuthType.$zero;
        }
        if (/** @type {any} */(false)) {
            /**
             * KeyName records which managed key file (~/.ssh/<name>) the private key
             * was taken from, so the edit form can restore the key source UI.
             * @member
             * @type {string | null | undefined}
             */
            this["key_name"] = undefined;
        }
        if (!("proxy_type" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["proxy_type"] = null;
        }
        if (!("proxy_addr" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["proxy_addr"] = null;
        }
        if (!("jump_host_id" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["jump_host_id"] = null;
        }
        if (!("upload_path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["upload_path"] = "";
        }
        if (!("default_cmd" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["default_cmd"] = null;
        }
        if (!("sort_order" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sort_order"] = 0;
        }
        if (!("color" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["color"] = null;
        }
        if (!("last_used_at" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["last_used_at"] = null;
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updated_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Connection instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Connection}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Connection(/** @type {Partial<Connection>} */($$parsedSource));
    }
}

/**
 * ConnectionForm is used for creating/updating connections from frontend.
 */
export class ConnectionForm {
    /**
     * Creates a new ConnectionForm instance.
     * @param {Partial<ConnectionForm>} [$$source = {}] - The source object to create the ConnectionForm.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("group_id" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["group_id"] = null;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("host" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("username" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["username"] = "";
        }
        if (!("auth_type" in $$source)) {
            /**
             * @member
             * @type {AuthType}
             */
            this["auth_type"] = AuthType.$zero;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["password"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["private_key"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["key_passphrase"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["key_name"] = undefined;
        }
        if (!("proxy_type" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["proxy_type"] = null;
        }
        if (!("proxy_addr" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["proxy_addr"] = null;
        }
        if (!("jump_host_id" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["jump_host_id"] = null;
        }
        if (!("upload_path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["upload_path"] = "";
        }
        if (!("default_cmd" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["default_cmd"] = null;
        }
        if (!("sort_order" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sort_order"] = 0;
        }
        if (!("color" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["color"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectionForm instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConnectionForm}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConnectionForm(/** @type {Partial<ConnectionForm>} */($$parsedSource));
    }
}

/**
 * DNSFieldSpec describes one credential input of a DNS provider.
 */
export class DNSFieldSpec {
    /**
     * Creates a new DNSFieldSpec instance.
     * @param {Partial<DNSFieldSpec>} [$$source = {}] - The source object to create the DNSFieldSpec.
     */
    constructor($$source = {}) {
        if (!("key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["key"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("secret" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["secret"] = false;
        }
        if (!("required" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["required"] = false;
        }
        if (!("placeholder" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["placeholder"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DNSFieldSpec instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DNSFieldSpec}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DNSFieldSpec(/** @type {Partial<DNSFieldSpec>} */($$parsedSource));
    }
}

/**
 * DNSProvider is a registry entry used by the frontend to render the
 * credential form dynamically.
 */
export class DNSProvider {
    /**
     * Creates a new DNSProvider instance.
     * @param {Partial<DNSProvider>} [$$source = {}] - The source object to create the DNSProvider.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("plugin" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["plugin"] = "";
        }
        if (!("fields" in $$source)) {
            /**
             * @member
             * @type {DNSFieldSpec[]}
             */
            this["fields"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DNSProvider instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DNSProvider}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("fields" in $$parsedSource) {
            $$parsedSource["fields"] = $$createField3_0($$parsedSource["fields"]);
        }
        return new DNSProvider(/** @type {Partial<DNSProvider>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const ForwardType = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    ForwardLocal: "local",
    ForwardRemote: "remote",
    ForwardDynamic: "dynamic",
};

export class Group {
    /**
     * Creates a new Group instance.
     * @param {Partial<Group>} [$$source = {}] - The source object to create the Group.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("parent_id" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["parent_id"] = null;
        }
        if (!("sort_order" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sort_order"] = 0;
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updated_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Group instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Group}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Group(/** @type {Partial<Group>} */($$parsedSource));
    }
}

export class PortForward {
    /**
     * Creates a new PortForward instance.
     * @param {Partial<PortForward>} [$$source = {}] - The source object to create the PortForward.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("connection_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["connection_id"] = "";
        }
        if (!("connection_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["connection_name"] = "";
        }
        if (!("connection_host" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["connection_host"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {ForwardType}
             */
            this["type"] = ForwardType.$zero;
        }
        if (!("local_host" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["local_host"] = "";
        }
        if (!("local_port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["local_port"] = 0;
        }
        if (!("remote_host" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["remote_host"] = "";
        }
        if (!("remote_port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["remote_port"] = 0;
        }
        if (!("auto_start" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["auto_start"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PortForward instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PortForward}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PortForward(/** @type {Partial<PortForward>} */($$parsedSource));
    }
}

export class QuickCommand {
    /**
     * Creates a new QuickCommand instance.
     * @param {Partial<QuickCommand>} [$$source = {}] - The source object to create the QuickCommand.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("command" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["command"] = "";
        }
        if (!("connection_id" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["connection_id"] = null;
        }
        if (!("sort_order" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sort_order"] = 0;
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updated_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QuickCommand instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {QuickCommand}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QuickCommand(/** @type {Partial<QuickCommand>} */($$parsedSource));
    }
}

/**
 * RemoteCert is one row of `acme.sh --list` output, optionally enriched with
 * `--info` data and the real certificate expiry. DaysLeft/DaysToExpiry are
 * distinct: acme.sh renews early (ARI suggests a window around 1/3 of the
 * cert lifetime), so the renewal countdown is much shorter than the expiry
 * countdown and the two must not be conflated in the UI.
 */
export class RemoteCert {
    /**
     * Creates a new RemoteCert instance.
     * @param {Partial<RemoteCert>} [$$source = {}] - The source object to create the RemoteCert.
     */
    constructor($$source = {}) {
        if (!("main_domain" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["main_domain"] = "";
        }
        if (!("key_length" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["key_length"] = "";
        }
        if (!("san_domains" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["san_domains"] = [];
        }
        if (!("ca" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ca"] = "";
        }
        if (!("created" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created"] = "";
        }
        if (!("renew" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["renew"] = "";
        }
        if (!("next_renew_time" in $$source)) {
            /**
             * epoch seconds, 0 = unknown
             * @member
             * @type {number}
             */
            this["next_renew_time"] = 0;
        }
        if (!("days_left" in $$source)) {
            /**
             * days until next renewal; nil = unknown
             * @member
             * @type {number | null}
             */
            this["days_left"] = null;
        }
        if (!("expires_at" in $$source)) {
            /**
             * real cert notAfter, epoch seconds, 0 = unknown
             * @member
             * @type {number}
             */
            this["expires_at"] = 0;
        }
        if (!("days_to_expiry" in $$source)) {
            /**
             * days until the cert actually expires; nil = unknown
             * @member
             * @type {number | null}
             */
            this["days_to_expiry"] = null;
        }
        if (!("ecc" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ecc"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RemoteCert instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RemoteCert}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("san_domains" in $$parsedSource) {
            $$parsedSource["san_domains"] = $$createField2_0($$parsedSource["san_domains"]);
        }
        return new RemoteCert(/** @type {Partial<RemoteCert>} */($$parsedSource));
    }
}

/**
 * RemoteCertInfo holds `acme.sh --info -d <domain>` key=value output.
 */
export class RemoteCertInfo {
    /**
     * Creates a new RemoteCertInfo instance.
     * @param {Partial<RemoteCertInfo>} [$$source = {}] - The source object to create the RemoteCertInfo.
     */
    constructor($$source = {}) {
        if (!("domain" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["domain"] = "";
        }
        if (!("fields" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: string }}
             */
            this["fields"] = {};
        }
        if (!("next_renew_time" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["next_renew_time"] = 0;
        }
        if (!("next_renew_time_str" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["next_renew_time_str"] = "";
        }
        if (!("cert_create_time" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["cert_create_time"] = "";
        }
        if (!("cert_path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["cert_path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RemoteCertInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RemoteCertInfo}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("fields" in $$parsedSource) {
            $$parsedSource["fields"] = $$createField1_0($$parsedSource["fields"]);
        }
        return new RemoteCertInfo(/** @type {Partial<RemoteCertInfo>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = DNSFieldSpec.createFrom;
const $$createType3 = $Create.Array($$createType2);
