package ssh

import (
	"fmt"
	"sync"
	"time"

	"golang.org/x/crypto/ssh"

	"vshell/internal/crypto"
	"vshell/internal/models"
)

type Manager struct {
	mu       sync.RWMutex
	clients  map[string]*ssh.Client // connectionID -> SSH client
	sessions map[string]*Session    // sessionID -> terminal session
	connSess map[string][]string    // connectionID -> []sessionID
	crypto   *crypto.CryptoService
	onEvent  func(event string, data any)
}

func NewManager(cryptoSvc *crypto.CryptoService, onEvent func(string, any)) *Manager {
	return &Manager{
		clients:  make(map[string]*ssh.Client),
		sessions: make(map[string]*Session),
		connSess: make(map[string][]string),
		crypto:   cryptoSvc,
		onEvent:  onEvent,
	}
}

// Connect creates a new terminal session on the given connection.
// sessionID is a unique identifier for this session (generated by caller).
func (m *Manager) Connect(conn *models.Connection, sessionID string) (*Session, error) {
	config, err := m.buildSSHConfig(conn)
	if err != nil {
		return nil, fmt.Errorf("build ssh config: %w", err)
	}

	if conn.JumpHostID != nil && *conn.JumpHostID != "" {
		return nil, fmt.Errorf("jump host connections not yet implemented")
	}

	addr := fmt.Sprintf("%s:%d", conn.Host, conn.Port)

	m.mu.Lock()
	// Reuse existing client if we already have one for this connection
	client, exists := m.clients[conn.ID]
	m.mu.Unlock()

	if !exists {
		client, err = ssh.Dial("tcp", addr, config)
		if err != nil {
			return nil, fmt.Errorf("dial %s: %w", addr, err)
		}
		m.mu.Lock()
		m.clients[conn.ID] = client
		m.mu.Unlock()
	}

	session, err := newSession(client, sessionID, m.onEvent)
	if err != nil {
		// If this was the first session and it failed, clean up the client
		if !exists {
			m.mu.Lock()
			delete(m.clients, conn.ID)
			m.mu.Unlock()
			client.Close()
		}
		return nil, fmt.Errorf("create session: %w", err)
	}

	m.mu.Lock()
	m.sessions[sessionID] = session
	m.connSess[conn.ID] = append(m.connSess[conn.ID], sessionID)
	m.mu.Unlock()

	return session, nil
}

// DisconnectSession closes a single session. If it's the last session for the
// connection, the SSH client is also closed.
func (m *Manager) DisconnectSession(sessionID string) {
	m.mu.Lock()
	s, ok := m.sessions[sessionID]
	if ok {
		delete(m.sessions, sessionID)
	}
	m.mu.Unlock()

	if !ok {
		return
	}

	connID := s.ID() // Session.id stores the sessionID
	s.Close()

	// Find and remove from connSess
	m.mu.Lock()
	for cid, sids := range m.connSess {
		for i, sid := range sids {
			if sid == sessionID {
				m.connSess[cid] = append(sids[:i], sids[i+1:]...)
				if len(m.connSess[cid]) == 0 {
					delete(m.connSess, cid)
					if client, ok := m.clients[cid]; ok {
						client.Close()
						delete(m.clients, cid)
					}
				}
				break
			}
		}
	}
	m.mu.Unlock()

	_ = connID
}

// Disconnect closes all sessions and the SSH client for a connection.
func (m *Manager) Disconnect(connectionID string) {
	m.mu.Lock()
	sids := m.connSess[connectionID]
	delete(m.connSess, connectionID)
	if client, ok := m.clients[connectionID]; ok {
		delete(m.clients, connectionID)
		m.mu.Unlock()
		client.Close()
	} else {
		m.mu.Unlock()
	}

	for _, sid := range sids {
		m.mu.Lock()
		s, ok := m.sessions[sid]
		delete(m.sessions, sid)
		m.mu.Unlock()
		if ok {
			s.Close()
		}
	}
}

func (m *Manager) GetSession(sessionID string) (*Session, bool) {
	m.mu.RLock()
	defer m.mu.RUnlock()
	s, ok := m.sessions[sessionID]
	return s, ok
}

// HasActiveSession returns true if the connection has at least one active terminal session.
func (m *Manager) HasActiveSession(connectionID string) bool {
	m.mu.RLock()
	defer m.mu.RUnlock()
	return len(m.connSess[connectionID]) > 0
}

func (m *Manager) buildSSHConfig(conn *models.Connection) (*ssh.ClientConfig, error) {
	authMethods := []ssh.AuthMethod{}

	switch conn.AuthType {
	case models.AuthPassword:
		password, err := m.crypto.Decrypt(conn.Password)
		if err != nil {
			return nil, fmt.Errorf("decrypt password: %w", err)
		}
		authMethods = append(authMethods, ssh.Password(password))

	case models.AuthPrivateKey:
		keyData, err := m.crypto.Decrypt(conn.PrivateKey)
		if err != nil {
			return nil, fmt.Errorf("decrypt private key: %w", err)
		}
		var signer ssh.Signer
		if conn.KeyPassphrase != "" {
			passphrase, err := m.crypto.Decrypt(conn.KeyPassphrase)
			if err != nil {
				return nil, fmt.Errorf("decrypt key passphrase: %w", err)
			}
			signer, err = ssh.ParsePrivateKeyWithPassphrase([]byte(keyData), []byte(passphrase))
			if err != nil {
				return nil, fmt.Errorf("parse private key with passphrase: %w", err)
			}
		} else {
			signer, err = ssh.ParsePrivateKey([]byte(keyData))
			if err != nil {
				return nil, fmt.Errorf("parse private key: %w", err)
			}
		}
		authMethods = append(authMethods, ssh.PublicKeys(signer))

	case models.AuthAgent:
		return nil, fmt.Errorf("ssh agent auth not yet implemented")

	case models.AuthInteractive:
		password, err := m.crypto.Decrypt(conn.Password)
		if err != nil {
			return nil, fmt.Errorf("decrypt password: %w", err)
		}
		authMethods = append(authMethods, ssh.KeyboardInteractive(
			func(user, instruction string, questions []string, echos []bool) ([]string, error) {
				answers := make([]string, len(questions))
				for i := range questions {
					answers[i] = password
				}
				return answers, nil
			},
		))

	default:
		return nil, fmt.Errorf("unsupported auth type: %s", conn.AuthType)
	}

	return &ssh.ClientConfig{
		User:            conn.Username,
		Auth:            authMethods,
		HostKeyCallback: ssh.InsecureIgnoreHostKey(),
		Timeout:         10 * time.Second,
	}, nil
}

func (m *Manager) NewMonitorSession(connectionID string) (*ssh.Session, *ssh.Client, error) {
	m.mu.RLock()
	client, ok := m.clients[connectionID]
	m.mu.RUnlock()

	if !ok {
		return nil, nil, fmt.Errorf("no active session for connection %s", connectionID)
	}

	session, err := client.NewSession()
	if err != nil {
		return nil, nil, fmt.Errorf("new monitor session: %w", err)
	}

	return session, client, nil
}

// WriteStdin writes data to the stdin pipe of the session identified by sessionID.
func (m *Manager) WriteStdin(sessionID string, data []byte) error {
	m.mu.RLock()
	s, ok := m.sessions[sessionID]
	m.mu.RUnlock()

	if !ok {
		return fmt.Errorf("no active session %s", sessionID)
	}

	_, err := s.WriteStdin(data)
	return err
}

// ResizeWindow resizes the PTY for the session identified by sessionID.
func (m *Manager) ResizeWindow(sessionID string, rows, cols int) error {
	m.mu.RLock()
	s, ok := m.sessions[sessionID]
	m.mu.RUnlock()

	if !ok {
		return fmt.Errorf("no active session %s", sessionID)
	}

	return s.ResizeWindow(rows, cols)
}

// ExecOnConnection runs a command on a new temporary session using the existing client.
func (m *Manager) ExecOnConnection(connectionID string, cmd string) (string, error) {
	m.mu.RLock()
	client, ok := m.clients[connectionID]
	m.mu.RUnlock()

	if !ok {
		return "", fmt.Errorf("no active session for connection %s", connectionID)
	}

	sess, err := client.NewSession()
	if err != nil {
		return "", fmt.Errorf("new session: %w", err)
	}
	defer sess.Close()

	out, err := sess.CombinedOutput(cmd)
	if err != nil {
		return string(out), fmt.Errorf("exec %q: %w", cmd, err)
	}
	return string(out), nil
}

// GetSSHClient returns the underlying SSH client for a connection.
func (m *Manager) GetSSHClient(connectionID string) (*ssh.Client, error) {
	m.mu.RLock()
	defer m.mu.RUnlock()

	client, ok := m.clients[connectionID]
	if !ok {
		return nil, fmt.Errorf("no active session for connection %s", connectionID)
	}
	return client, nil
}
