#!/bin/bash
set -e

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
BIN_DIR="$ROOT_DIR/bin"
BUILD_DIR="$ROOT_DIR/build/darwin"
BINARY="$BIN_DIR/vshell"
APP_NAME="vshell"
APP_BUNDLE="$BIN_DIR/$APP_NAME.app"

# Step 1: Build the binary
echo "==> Building with wails3..."
cd "$ROOT_DIR"
wails3 build

if [ ! -f "$BINARY" ]; then
    echo "ERROR: Binary not found at $BINARY"
    exit 1
fi

# Step 2: Clean old app bundle and create structure
echo "==> Creating app bundle..."
rm -rf "$APP_BUNDLE"
mkdir -p "$APP_BUNDLE/Contents/MacOS"
mkdir -p "$APP_BUNDLE/Contents/Resources"

# Step 3: Copy binary
echo "  -> Copying binary..."
cp "$BINARY" "$APP_BUNDLE/Contents/MacOS/$APP_NAME"
chmod +x "$APP_BUNDLE/Contents/MacOS/$APP_NAME"

# Step 4: Copy Info.plist (generated by wails from build/config.yml)
echo "  -> Copying Info.plist..."
cp "$BUILD_DIR/Info.plist" "$APP_BUNDLE/Contents/Info.plist"

# Step 5: Copy icon and asset catalog
echo "  -> Copying icons..."
cp "$BUILD_DIR/icons.icns" "$APP_BUNDLE/Contents/Resources/icons.icns"
cp "$BUILD_DIR/Assets.car" "$APP_BUNDLE/Contents/Resources/Assets.car"

echo "==> Done: $APP_BUNDLE"
echo "    Run with: open $APP_BUNDLE"

# Step 6: Create DMG
echo "==> Creating DMG..."

DMG_NAME="${APP_NAME}.dmg"
TMP_DIR="$BIN_DIR/dmg"

rm -rf "$TMP_DIR"
mkdir -p "$TMP_DIR"

cp -R "$APP_BUNDLE" "$TMP_DIR"

# 可选：增加 Applications 快捷方式
ln -s /Applications "$TMP_DIR/Applications"

rm -f "$BIN_DIR/$DMG_NAME"

hdiutil create \
    -volname "$APP_NAME" \
    -srcfolder "$TMP_DIR" \
    -ov \
    -format UDZO \
    "$BIN_DIR/$DMG_NAME"

rm -rf "$TMP_DIR"

echo "==> DMG Created:"
echo "    $BIN_DIR/$DMG_NAME"